/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package applet;

import java.awt.Component;
import java.awt.Container;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.JLabel;

/**
 *
 * @author Sukov
 */
public class KursnaLista extends javax.swing.JApplet {
 private static void dodadi(Container container, Component component, 
int gridx, int gridy, int gridwidth, int gridheight, int anchor, 
int fill) { 
GridBagConstraints gbc = new GridBagConstraints(gridx, gridy, 
gridwidth, gridheight, 1.0, 1.0, anchor, fill, new Insets(0,0,0,0), 0, 0); 
container.add(component, gbc); 
    }
    /**
     * Initializes the applet KursnaLista
     */
    @Override
    public void init() {
      JLabel drzava=new JLabel("Drzava");
      JLabel valuta=new JLabel("Valuta");
      JLabel kupi=new JLabel("Kupi");
      JLabel sreden=new JLabel("Sreden kurs");
      JLabel prodaj=new JLabel("Prodaj");
      
      setSize(500,200);
      setLayout(new GridBagLayout());
      
      dodadi(this,drzava,0,0,1,1,GridBagConstraints.CENTER,GridBagConstraints.BOTH);
      dodadi(this,valuta,1,0,1,1,GridBagConstraints.CENTER,GridBagConstraints.BOTH);
      dodadi(this,kupi,2,0,1,1,GridBagConstraints.CENTER,GridBagConstraints.BOTH);
      dodadi(this,prodaj,3,0,1,1,GridBagConstraints.CENTER,GridBagConstraints.BOTH);
      
      

        
      JLabel drzava1=new JLabel("Velika Britanija");
      JLabel valuta1=new JLabel("GBP");
      JLabel kupi1=new JLabel("76.27");
      JLabel sreden1=new JLabel("75.71");
      JLabel prodaj1=new JLabel("74.76");
      
         dodadi(this,drzava1,0,1,1,1,GridBagConstraints.CENTER,GridBagConstraints.BOTH);
      dodadi(this,valuta1,1,1,1,1,GridBagConstraints.CENTER,GridBagConstraints.BOTH);
      dodadi(this,kupi1,2,1,1,1,GridBagConstraints.CENTER,GridBagConstraints.BOTH);
      dodadi(this,prodaj1,3,1,1,1,GridBagConstraints.CENTER,GridBagConstraints.BOTH);
      
       JLabel drzava2=new JLabel("SAD");
      JLabel valuta2=new JLabel("USD");
      JLabel kupi2=new JLabel("47.58");
      JLabel sreden2=new JLabel("47.26");
      JLabel prodaj2=new JLabel("46.26");
      
         dodadi(this,drzava2,0,2,1,1,GridBagConstraints.CENTER,GridBagConstraints.BOTH);
      dodadi(this,valuta2,1,2,1,1,GridBagConstraints.CENTER,GridBagConstraints.BOTH);
      dodadi(this,kupi2,2,2,1,1,GridBagConstraints.CENTER,GridBagConstraints.BOTH);
      dodadi(this,prodaj2,3,2,1,1,GridBagConstraints.CENTER,GridBagConstraints.BOTH);
      
       JLabel drzava3=new JLabel("Evropska Unija");
      JLabel valuta3=new JLabel("EUR");
      JLabel kupi3=new JLabel("61.75");
      JLabel sreden3=new JLabel("61.5");
      JLabel prodaj3=new JLabel("61.35");
      
         dodadi(this,drzava3,0,3,1,1,GridBagConstraints.CENTER,GridBagConstraints.BOTH);
      dodadi(this,valuta3,1,3,1,1,GridBagConstraints.CENTER,GridBagConstraints.BOTH);
      dodadi(this,kupi3,2,3,1,1,GridBagConstraints.CENTER,GridBagConstraints.BOTH);
      dodadi(this,prodaj3,3,3,1,1,GridBagConstraints.CENTER,GridBagConstraints.BOTH);
      
       JLabel drzava4=new JLabel("Avstralija");
      JLabel valuta4=new JLabel("AUD");
      JLabel kupi4=new JLabel("49.83");
      JLabel sreden4=new JLabel("49.22");
      JLabel prodaj4=new JLabel("48.45");
      
         dodadi(this,drzava4,0,4,1,1,GridBagConstraints.CENTER,GridBagConstraints.BOTH);
      dodadi(this,valuta4,1,4,1,1,GridBagConstraints.CENTER,GridBagConstraints.BOTH);
      dodadi(this,kupi4,2,4,1,1,GridBagConstraints.CENTER,GridBagConstraints.BOTH);
      dodadi(this,prodaj4,3,4,1,1,GridBagConstraints.CENTER,GridBagConstraints.BOTH);
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
